name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "SPRING_DATASOURCE_URL=${{ secrets.DATASOURCE_URL }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test  # 테스트 제외하고 빌드

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Upload JAR to EC2 & Start
        run: |
          scp -C -o StrictHostKeyChecking=no -i ec2_key.pem build/libs/*.jar ubuntu@"${{ secrets.SERVER_IP }}":/home/ubuntu/app/backend-0.0.1-SNAPSHOT.jar

      - name: Set Executable Permission & Restart App
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@"${{ secrets.SERVER_IP }}" << 'EOF'
            chmod +x /home/ubuntu/app/backend-0.0.1-SNAPSHOT.jar
            nohup java -jar /home/ubuntu/app/backend-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
          EOF